escamboapp/config/routes.rb
Rails.application.routes.draw do

  post '/rate' => 'rater#create', :as => 'rate'
  get 'backoffice', to: 'backoffice/dashboard#index'
  get 'admin', to: 'backoffice/dashboard#index'

  namespace :backoffice do
    resources :send_mail, only: [:edit, :create]
    resources :categories, except: [:show,:destroy]
    resources :admins, except: [:show]
    resources :diagrams, only: [:index]
    get 'dashboard', to:'dashboard#index'
  end

  namespace :site do
    

    namespace :profile do
      resources :dashboard, only: [:index]
      resources :ads, only: [:index, :edit,:update,:new, :create]
    end
    get 'home', to: 'home#index'
    get 'search', to: 'search#ads'
    resources :ad_detail, only: [:index,:show]
    resources :categories, only: [:show]
    resources :comments, only: [:create]

  end

  devise_for :admins, :skip => [:registrantions]
  devise_for :members, controllers: { sessions: "members/sessions"}

  root 'site/home#index'

end

escamboapp/app/models/ad.rb
class Ad < ActiveRecord::Base


  #Constants
  QTT_PER_PAGE = 6

  #RatyRate gem
  ratyrate_rateable "quality"

  #Callbacks
  before_save :md_to_html

  #Associations
  belongs_to :category, counter_cache: true
  belongs_to :member
  has_many :comments

  #Validates
  validates :title, :description_md,:description_short, :category, :price, :picture, :finish_date, presence: true
  validates :price, numericality: {greater_than: 0}


  #Paperclip
  has_attached_file :picture, styles: { 
    large: "800x300#",
  	medium: "320x150#", 
  	thumb: "100x100>" 
  	}, default_url: "/images/:style/missing.png"
  validates_attachment_content_type :picture, content_type: /\Aimage\/.*\z/

  #gem money-rails
  monetize :price_cents

  #Scopes
  
  scope :descending_order,  -> (page) {
    order(created_at: :desc).page(page).per(QTT_PER_PAGE)
  }
  
  scope :search, -> (query,page){
    where("lower(title) LIKE ?", "%#{query.downcase}%").page(page).per(QTT_PER_PAGE)
  }

  scope :last_six, -> {limit(QTT_PER_PAGE).order(created_at: :desc)}
  scope :to_the, -> (current_member) { where(member: current_member) }
  scope :get_all_ads_by_category, -> (category_id,page) {where(category_id: category_id).page(page).per(QTT_PER_PAGE)}


  private
    #Method to convert markdown to html
    def md_to_html
      options = {
          filter_html: true,
          link_attributes: {
            rel: "nofollow",
            target: "_blank"
          }
      }

      extensions = {
        space_after_headers: true,
        autolink: true
      }

      renderer = Redcarpet::Render::HTML.new(options)
      markdown = Redcarpet::Markdown.new(renderer, extensions)

      self.description = markdown.render(self.description_md)
    end
end

escamboapp/app/models/admin.rb
class Admin < ActiveRecord::Base

	#Enums
	enum role: { :full_access => 0, :restricted_access => 1 }

  #Scopes
  scope :with_full_access, -> {where(role: 0)}
  scope :with_restricted_access, -> {where(role: 1)}

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
         
end

escamboapp/app/models/average_cache.rb
class AverageCache < ActiveRecord::Base
  belongs_to :rater, :class_name => "Member"
  belongs_to :rateable, :polymorphic => true
end

escamboapp/app/models/category.rb
class Category < ActiveRecord::Base
	
	#Gem FriendlyId
	include FriendlyId
	friendly_id :description, use: :slugged

	#Associations
	has_many :ads

	#Validates
	validates_presence_of :description

	#Scopes

	scope :order_by_description, -> {order(:description)}
end

escamboapp/app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :member
  belongs_to :ad
end

escamboapp/app/models/member.rb
class Member < ActiveRecord::Base

	# Configuracao para quem vai avaliar o anuncio
  ratyrate_rater

	#Associations
  has_many :ads
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

escamboapp/app/models/overall_average.rb
class OverallAverage < ActiveRecord::Base
  belongs_to :rateable, :polymorphic => true
end

escamboapp/app/models/rate.rb
class Rate < ActiveRecord::Base
  belongs_to :rater, :class_name => "Member"
  belongs_to :rateable, :polymorphic => true

  #attr_accessible :rate, :dimension

end

escamboapp/app/models/rating_cache.rb
class RatingCache < ActiveRecord::Base
  belongs_to :cacheable, :polymorphic => true
end

escamboapp/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_filter :store_current_location, :unless => :devise_controller?

  # Pundit
  include Pundit

  # Manage pundit errors
  rescue_from Pundit::NotAuthorizedError, with: :user_not_authorized

  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  #Set Layout
  layout :layout_by_resource

  protected

  def layout_by_resource
  	if devise_controller? && resource_name == :admin
  		"backoffice_devise"
    elsif devise_controller? && resource_name == :member
      "site_devise"
  	else
  		"application"
  	end
  end

  def user_not_authorized
  flash[:alert] = t('messages.punditError')
  redirect_to(request.referrer || root_path)
  end


  private

   # Redirecionar o usuario para a ultima tela que ele estava antes de logar
  def store_current_location
    store_location_for(:member, request.url)
  end
end

escamboapp/app/controllers/backoffice_controller.rb
class BackofficeController < ApplicationController
  before_action :authenticate_admin!
  layout "backoffice"

  def pundit_user
  	current_admin # current_user to Pundit
  end

end

escamboapp/app/controllers/rater_controller.rb
class RaterController < ApplicationController

  def create
    if member_signed_in?
      obj = params[:klass].classify.constantize.find(params[:id])
      obj.rate params[:score].to_f, current_member, params[:dimension]

      render :json => true
    else
      render :json => false
    end
  end
end

escamboapp/app/controllers/site/home_controller.rb
class Site::HomeController < SiteController
  def index
  	@categories = Category.order_by_description
  	@ads = Ad.descending_order(params[:page])
  end
end

escamboapp/app/controllers/site_controller.rb
class SiteController < ApplicationController
  layout "site"
end

escamboapp/app/helpers/application_helper.rb
module ApplicationHelper
	def md_to_html(text)
		options = {
		    filter_html: true,
		    link_attributes: {
		      rel: "nofollow",
		      target: "_blank"
		    }
		}

		extensions = {
		  space_after_headers: true,
		  autolink: true
		}

		renderer = Redcarpet::Render::HTML.new(options)
		markdown = Redcarpet::Markdown.new(renderer, extensions)

		markdown.render(text).html_safe
		
	end

	def current_user
		current_member
	end
end

escamboapp/app/helpers/site/ad_detail_helper.rb
module Site::AdDetailHelper
end

escamboapp/app/helpers/site/categories_helper.rb
module Site::CategoriesHelper
end

escamboapp/app/helpers/site/comments_helper.rb
module Site::CommentsHelper
end

escamboapp/app/helpers/site/home_helper.rb
module Site::HomeHelper
end

escamboapp/app/helpers/site/search_helper.rb
module Site::SearchHelper
end

escamboapp/app/views/backoffice/admins/shared/_form.html.erb
<h1 class="page-header">Administradores</h1>
 <% if @admin.errors.any? %>
    <div class="alert alert-danger alert-dismissable">
        <button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button>
          <ul>
            <% @admin.errors.full_messages.each do |message| %>
              <li><%= message %></li>
            <% end %>
          </ul>
    </div>
  <% end %>
<div class="panel panel-default">
    <div class="panel-heading">
        <%= action %>
    </div>
    <div class="panel-body">
        <div class="col-lg-6">
            <%= form_for([:backoffice, @admin]) do |f| %>
                <div class="form-group">
                    <%= f.label :name %>
                    <%= f.text_field :name, class: "form-control", placeholder: "Ex: John" %>
                </div>
                <div class="form-group">
                    <%= f.label :email %>
                    <%= f.text_field :email, class: "form-control", placeholder: "Ex: email@email" %>
                </div>
                <% if policy(@admin).edit? %>
                    <div class="form-group">
                        <%= f.label :role %>
                        <%= f.collection_radio_buttons(:role, options_for_roles,:id,:description) do |b| %>
                           <div class="radio">
                              <%= b.label { b.radio_button + b.text } %>
                            </div>
                        <% end %>
                    </div>
                <% end %>
                <div class="form-group">
                    <%= f.label :password %>
                    <%= f.password_field :password, class: "form-control", placeholder: "Senha" %>
                </div>
                <div class="form-group">
                    <%= f.label :password_confirmation %>
                    <%= f.password_field :password_confirmation, class: "form-control",
                        placeholder: "Confirmação de Senha" %>
                </div>
                <button type="submit" class="btn btn-default">Salvar</button>
            <% end %>
        </div>
    </div>
    <!-- /.panel-body -->
</div>

escamboapp/app/views/backoffice/admins/shared/_send_mail_modal.html.erb
<div class="modal fade" id="sendMailModal" tabindex="-1" role="dialog" aria-labelledby="sendMailModalLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="sendMailModalLabel"><%= t('labels.new_message') %></h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <%= form_tag(backoffice_send_mail_index_path, remote:true) do %>
          <div class="form-group">
            <label for="recipient-name" class="col-form-label"><%= t('labels.recipient') %></label>
            <%= text_field_tag(:'recipient-text',nil,class: "form-control", readonly: true) %>
          </div>
          <div class="form-group">
            <label for="subject-name" class="col-form-label"><%= t('labels.subject') %></label>
             <%= text_field_tag(:'subject-text',nil,class: "form-control") %>
          </div>
          <div class="form-group">
            <label for="message-text" class="col-form-label"><%= t('labels.message') %></label>
             <%= text_area_tag(:'message-text',nil,class: "form-control") %>
          </div>
          </div>
          <div class="modal-footer">
            <button type="button" class="btn btn-secondary" data-dismiss="modal"><%= t('buttons.close') %></button>
            <%= submit_tag t('buttons.send_message'), class: "btn btn-primary" %>
          </div>
        <% end %>
    </div>
  </div>
</div>

escamboapp/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Escamboapp</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>
<%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>

</body>
</html>

escamboapp/app/views/layouts/backoffice.html.erb
<!DOCTYPE html>
<html lang="en">

<head>

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">
	 <title>BackOffice - Escamboapp</title>
	  <%= stylesheet_link_tag    'application', media: 'all' %>
	  <%= stylesheet_link_tag    'backoffice', media: 'all' %>
	 
	  <%= csrf_meta_tags %>
</head>

<body>
	<div id="wrapper">
		<%= render partial: "layouts/backoffice_shared/navigation" %>
		<div id="page-wrapper">
		    <div class="container-fluid">
		        <div class="row">
		            <div class="col-lg-12">
						<%= yield %>
		            </div>
		        </div>
		    </div>
		</div>
	</div>

	<%= javascript_include_tag 'application' %>
	<%= javascript_include_tag 'backoffice' %>
	
	<%= render partial: 'layouts/shared/notifications'  %>

	
</body>
</html>

escamboapp/app/views/layouts/backoffice_devise.html.erb
<!DOCTYPE html>
<html lang="en">

<head>

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">
	 <title>BackOffice - Escamboapp</title>
	  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
	  <%= stylesheet_link_tag    'backoffice', media: 'all', 'data-turbolinks-track' => true %>
	  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
	  <%= javascript_include_tag 'backoffice', 'data-turbolinks-track' => true %>
	  <%= csrf_meta_tags %>
</head>

<body>
	<%= yield %>
</div>
</body>

</html>

escamboapp/app/views/layouts/backoffice_shared/_navigation.html.erb
        <!-- Navigation -->
        <nav class="navbar navbar-default navbar-static-top" role="navigation" style="margin-bottom: 0">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="index.html">BackOffice - Escamboapp</a>
            </div>
            <!-- /.navbar-header -->

            <ul class="nav navbar-top-links navbar-right">

                
                
                <li><%= current_admin.email %></li>
                <!-- /.dropdown -->
                <li class="dropdown">
                    <a class="dropdown-toggle" data-toggle="dropdown" href="#">
                        <i class="fa fa-user fa-fw"></i> <i class="fa fa-caret-down"></i>
                    </a>
                    <ul class="dropdown-menu dropdown-user">
                        <%= link_to destroy_admin_session_path, method: :delete do %>
                            <i class="fa fa-sign-out fa-fw"></i> Sair
                        <% end %>
                    </ul>
                    <!-- /.dropdown-user -->
                </li>
                <!-- /.dropdown -->
            </ul>
            <!-- /.navbar-top-links -->

            <div class="navbar-default sidebar" role="navigation">
                <div class="sidebar-nav navbar-collapse">
                    <ul class="nav" id="side-menu">
                        <li>
                            <%= link_to backoffice_path do %>
                                <i class="fa fa-dashboard fa-fw"></i> Dashboard
                            <% end %>
                        </li>
                        <li>
                            <%= link_to backoffice_categories_path do %>
                                <i class="fa fa-th-list fa-fw"></i> Categorias
                            <% end %>
                        </li>
                        <li>
                            <%= link_to backoffice_admins_path do %>
                                <i class="fa fa-users fa-fw"></i> Administradores
                            <% end %>
                        </li>
                        <% if Rails.env.development? %>
                            <li>
                                <%= link_to backoffice_diagrams_path do %>
                                    <i class="fa fa-database fa-fw"></i> Diagrama ER
                                <% end %>
                            </li>
                        <% end %>
                    </ul>
                </div>
                <!-- /.sidebar-collapse -->
            </div>
            <!-- /.navbar-static-side -->
        </nav>

escamboapp/app/views/layouts/profile.html.erb
<!DOCTYPE html>
<html lang="en">

  <head>

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>Escamboapp</title>
    	<%= stylesheet_link_tag  'application', media: 'all'%>
        <%= stylesheet_link_tag  'site', media: 'all' %>
        <%= stylesheet_link_tag  'site/profile', media: 'all'%>
    	<%= csrf_meta_tags %>
  </head>

  <body>
  	<%= render partial: "layouts/site_shared/navigation" %>
    <div id="wrapper" >
        <!-- Sidebar -->
        <div id="sidebar-wrapper">
            <ul class="sidebar-nav">
                <li class="sidebar-brand">
                    <a href="#">
                        Start Bootstrap
                    </a>
                </li>
                <li>
                    <%= link_to site_profile_dashboard_index_path do %>
                        <span>Dashboard</span>
                    <% end %>
                </li>
                <li>
                    <%= link_to site_profile_ads_path do %>
                        <span>Meus anúncios</span>
                    <% end %>
                </li>
                <li>
                    <%= link_to new_site_profile_ad_path do %>
                        <span>Novo Anúncio</span>
                    <% end %>
                </li>
            </ul>
        </div>
        <!-- /#sidebar-wrapper -->

        <!-- Page Content -->
        <div id="page-content-wrapper">
            <div class="container-fluid">
              <%= yield %>
            </div>
        </div>
    </div>

        <%= javascript_include_tag 'application' %>
        <%= javascript_include_tag 'site'%>
        <%= javascript_include_tag 'site/profile' %>
        <%#= javascript_include_tag 'site/profile/ads' %>

        <%= yield :javascripts %>

        <%= render partial: 'layouts/shared/notifications'  %>

  </body>

</html>

escamboapp/app/views/layouts/site.html.erb
<!DOCTYPE html>
<html lang="en">

  <head>

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>Escamboapp</title>
  	  <%= stylesheet_link_tag    'application', media: 'all'%>
  	  <%= stylesheet_link_tag    'site', media: 'all' %>
      <%= csrf_meta_tags %>
  </head>

  <body>
    <div id="global-spin" class="loading" style="display: none">Loading&#8230;</div>
  	<%= render partial: "layouts/site_shared/navigation" %>

    <!-- Page Content -->
    <div class="container">
      <%= form_tag site_search_path, method: :get do %>
        <div class="row">
          <div class="well well-sm">
             <div class="row">
              <div class="col-xs-3 col-sm-3 col-md-3 col-lg-3">
              </div>

                <div class="col-lg-6">
                  <div class="input-group">
                    <%= text_field_tag(:q, params[:q],{class: "form-control", placeholder: "Pesquisar por..."}) %>
                    <span class="input-group-btn">
                      <%= submit_tag("Pesquisar", class: "btn btn-default") %>
                    </span>
                  </div><!-- /input-group -->
                </div><!-- /.col-lg-6 -->

                <div class="col-xs-3 col-sm-3 col-md-3 col-lg-3"></div>
              </div><!-- /.row -->
          </div>
        </div>
      <% end %>
        <div class="row">
            <!-- SideBar -->
           <%= render partial: 'layouts/site_shared/sidebar' %>

            <div id="home_detail" class="col-md-9">
                <% if controller_path == "site/home" %>
                  <!-- Carousel -->
                  <%= render partial: 'layouts/site_shared/carousel' %>
                <% end %>
                <div class="row">
                  <%= yield %>
                </div>

            </div>

        </div>

    </div>


		<%= render partial: "layouts/site_shared/footer" %>
    <%= javascript_include_tag 'application' %>
    <%= javascript_include_tag 'site' %>
    <%= render partial: 'layouts/shared/notifications'  %>
  </body>

</html>

escamboapp/app/views/layouts/site_devise.html.erb
<!DOCTYPE html>
<html lang="en">

<head>

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">
	 <title>BackOffice - Escamboapp</title>
	  <%= stylesheet_link_tag    'application', media: 'all' %>
	  <%= stylesheet_link_tag    'backoffice', media: 'all' %>
	  <%= javascript_include_tag 'application' %>
	  <%= javascript_include_tag 'backoffice' %>
	  <%= csrf_meta_tags %>
</head>

<body>
	<%= yield %>
</div>
</body>

</html>

escamboapp/app/views/layouts/site_shared/_carousel.html.erb
<div class="row carousel-holder">
    <div class="col-md-12">
        <div id="carousel-example-generic" class="carousel slide" data-ride="carousel">
            <ol class="carousel-indicators">
                <li data-target="#carousel-example-generic" data-slide-to="0" class="active"></li>
                <li data-target="#carousel-example-generic" data-slide-to="1"></li>
                <li data-target="#carousel-example-generic" data-slide-to="2"></li>
            </ol>
            <div class="carousel-inner">
                <div class="item active">
                    <img class="slide-image" src="http://placehold.it/800x300" alt="">
                </div>
                <div class="item">
                    <img class="slide-image" src="http://placehold.it/800x300" alt="">
                </div>
                <div class="item">
                    <img class="slide-image" src="http://placehold.it/800x300" alt="">
                </div>
            </div>
            <a class="left carousel-control" href="#carousel-example-generic" data-slide="prev">
                <span class="glyphicon glyphicon-chevron-left"></span>
            </a>
            <a class="right carousel-control" href="#carousel-example-generic" data-slide="next">
                <span class="glyphicon glyphicon-chevron-right"></span>
            </a>
        </div>
    </div>

</div>

escamboapp/app/views/layouts/site_shared/_footer.html.erb
    <div class="container">
        <hr>
        <!-- Footer -->
        <footer>
            <div class="row">
                <div class="col-lg-12">
                    <p>Copyright &copy; EscamboApp <%= Date.today.year %></p>
                </div>
            </div>
        </footer>

    </div>

escamboapp/app/views/layouts/site_shared/_navigation.html.erb
 <nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
        <div class="container">
            <!-- Brand and toggle get grouped for better mobile display -->
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <%= link_to t('labels.app_name'), root_path,class: "navbar-brand"%>
            </div>
            <!-- Collect the nav links, forms, and other content for toggling -->
            <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                <ul class="nav navbar-nav pull-right">
                    <% unless member_signed_in? %>
                        <li>
                           <%= link_to "Login", new_member_session_path %>
                        </li>
                        <li>
                            <%= link_to "Cadastrar-se", new_member_registration_path %>
                        </li>
                    <% else %>
                        <li>
                           <%= link_to current_member.email, "#" %>
                        </li>
                        <li>
                           <%= link_to "Perfil", site_profile_dashboard_index_path %>
                        </li>
                        <li>
                           <%= link_to "Logout", destroy_member_session_path, method: :delete %>
                        </li>
                    <% end %>
                </ul>
            </div>
            <!-- /.navbar-collapse -->
        </div>
        <!-- /.container -->
    </nav>

escamboapp/app/views/layouts/site_shared/_sidebar.html.erb
 <div id="home_sidebar" class="col-md-3">
	<p class="lead">Categorias</p>
	<% @categories.each do |category| %>
	    <%= link_to "#{category.description} (#{category.ads_count})" , site_category_path(category.friendly_id), class: "list-group-item" %>
	<% end %>
</div>