escamboapp/config/routes.rb
Rails.application.routes.draw do

  post '/rate' => 'rater#create', :as => 'rate'
  get 'backoffice', to: 'backoffice/dashboard#index'
  get 'admin', to: 'backoffice/dashboard#index'

  namespace :backoffice do
    resources :send_mail, only: [:edit, :create]
    resources :categories, except: [:show,:destroy]
    resources :admins, except: [:show]
    resources :diagrams, only: [:index]
    get 'dashboard', to:'dashboard#index'
  end

  namespace :site do
    

    namespace :profile do
      resources :dashboard, only: [:index]
      resources :ads, only: [:index, :edit,:update,:new, :create]
    end
    get 'home', to: 'home#index'
    get 'search', to: 'search#ads'
    resources :ad_detail, only: [:index,:show]
    resources :categories, only: [:show]
    resources :comments, only: [:create]

  end

  devise_for :admins, :skip => [:registrantions]
  devise_for :members, controllers: { sessions: "members/sessions"}

  root 'site/home#index'

end

escamboapp/app/models/ad.rb
class Ad < ActiveRecord::Base


  #Constants
  QTT_PER_PAGE = 6

  #RatyRate gem
  ratyrate_rateable "quality"

  #Callbacks
  before_save :md_to_html

  #Associations
  belongs_to :category, counter_cache: true
  belongs_to :member
  has_many :comments

  #Validates
  validates :title, :description_md,:description_short, :category, :price, :picture, :finish_date, presence: true
  validates :price, numericality: {greater_than: 0}


  #Paperclip
  has_attached_file :picture, styles: { 
    large: "800x300#",
  	medium: "320x150#", 
  	thumb: "100x100>" 
  	}, default_url: "/images/:style/missing.png"
  validates_attachment_content_type :picture, content_type: /\Aimage\/.*\z/

  #gem money-rails
  monetize :price_cents

  #Scopes
  
  scope :descending_order,  -> (page) {
    order(created_at: :desc).page(page).per(QTT_PER_PAGE)
  }
  
  scope :search, -> (query,page){
    where("lower(title) LIKE ?", "%#{query.downcase}%").page(page).per(QTT_PER_PAGE)
  }

  scope :last_six, -> {limit(QTT_PER_PAGE).order(created_at: :desc)}
  scope :to_the, -> (current_member) { where(member: current_member) }
  scope :get_all_ads_by_category, -> (category_id,page) {where(category_id: category_id).page(page).per(QTT_PER_PAGE)}


  private
    #Method to convert markdown to html
    def md_to_html
      options = {
          filter_html: true,
          link_attributes: {
            rel: "nofollow",
            target: "_blank"
          }
      }

      extensions = {
        space_after_headers: true,
        autolink: true
      }

      renderer = Redcarpet::Render::HTML.new(options)
      markdown = Redcarpet::Markdown.new(renderer, extensions)

      self.description = markdown.render(self.description_md)
    end
end

escamboapp/app/models/admin.rb
class Admin < ActiveRecord::Base

	#Enums
	enum role: { :full_access => 0, :restricted_access => 1 }

  #Scopes
  scope :with_full_access, -> {where(role: 0)}
  scope :with_restricted_access, -> {where(role: 1)}

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
         
end

escamboapp/app/models/average_cache.rb
class AverageCache < ActiveRecord::Base
  belongs_to :rater, :class_name => "Member"
  belongs_to :rateable, :polymorphic => true
end

escamboapp/app/models/category.rb
class Category < ActiveRecord::Base
	
	#Gem FriendlyId
	include FriendlyId
	friendly_id :description, use: :slugged

	#Associations
	has_many :ads

	#Validates
	validates_presence_of :description

	#Scopes

	scope :order_by_description, -> {order(:description)}
end

escamboapp/app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :member
  belongs_to :ad
end

escamboapp/app/models/member.rb
class Member < ActiveRecord::Base

	# Configuracao para quem vai avaliar o anuncio
  ratyrate_rater

	#Associations
  has_many :ads
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

escamboapp/app/models/overall_average.rb
class OverallAverage < ActiveRecord::Base
  belongs_to :rateable, :polymorphic => true
end

escamboapp/app/models/rate.rb
class Rate < ActiveRecord::Base
  belongs_to :rater, :class_name => "Member"
  belongs_to :rateable, :polymorphic => true

  #attr_accessible :rate, :dimension

end

escamboapp/app/models/rating_cache.rb
class RatingCache < ActiveRecord::Base
  belongs_to :cacheable, :polymorphic => true
end

escamboapp/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_filter :store_current_location, :unless => :devise_controller?

  # Pundit
  include Pundit

  # Manage pundit errors
  rescue_from Pundit::NotAuthorizedError, with: :user_not_authorized

  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  #Set Layout
  layout :layout_by_resource

  protected

  def layout_by_resource
  	if devise_controller? && resource_name == :admin
  		"backoffice_devise"
    elsif devise_controller? && resource_name == :member
      "site_devise"
  	else
  		"application"
  	end
  end

  def user_not_authorized
  flash[:alert] = t('messages.punditError')
  redirect_to(request.referrer || root_path)
  end


  private

   # Redirecionar o usuario para a ultima tela que ele estava antes de logar
  def store_current_location
    store_location_for(:member, request.url)
  end
end

escamboapp/app/controllers/backoffice_controller.rb
class BackofficeController < ApplicationController
  before_action :authenticate_admin!
  layout "backoffice"

  def pundit_user
  	current_admin # current_user to Pundit
  end

end

escamboapp/app/controllers/rater_controller.rb
class RaterController < ApplicationController

  def create
    if member_signed_in?
      obj = params[:klass].classify.constantize.find(params[:id])
      obj.rate params[:score].to_f, current_member, params[:dimension]

      render :json => true
    else
      render :json => false
    end
  end
end

escamboapp/app/controllers/site/ad_detail_controller.rb
class Site::AdDetailController < SiteController
	def show
		@categories = Category.order_by_description
		@ad = Ad.find(params[:id])
	end
end

escamboapp/app/controllers/site/home_controller.rb
class Site::HomeController < SiteController
  def index
  	@categories = Category.order_by_description
  	@ads = Ad.descending_order(params[:page])
  end
end

escamboapp/app/controllers/site_controller.rb
class SiteController < ApplicationController
  layout "site"
end

escamboapp/app/helpers/application_helper.rb
module ApplicationHelper
	def md_to_html(text)
		options = {
		    filter_html: true,
		    link_attributes: {
		      rel: "nofollow",
		      target: "_blank"
		    }
		}

		extensions = {
		  space_after_headers: true,
		  autolink: true
		}

		renderer = Redcarpet::Render::HTML.new(options)
		markdown = Redcarpet::Markdown.new(renderer, extensions)

		markdown.render(text).html_safe
		
	end

	def current_user
		current_member
	end
end

escamboapp/app/helpers/backoffice/admins_helper.rb
module Backoffice::AdminsHelper
	OptionsForRoles = Struct.new(:id,:description)

	def options_for_roles
		#Map devolve um array depois de executar uma funcao
		Admin.roles_i18n.map do |key,value|
			OptionsForRoles.new(key,value)
		end
	end
end

escamboapp/app/helpers/site/ad_detail_helper.rb
module Site::AdDetailHelper
end

escamboapp/app/helpers/site/categories_helper.rb
module Site::CategoriesHelper
end

escamboapp/app/helpers/site/comments_helper.rb
module Site::CommentsHelper
end

escamboapp/app/helpers/site/home_helper.rb
module Site::HomeHelper
end

escamboapp/app/helpers/site/search_helper.rb
module Site::SearchHelper
end

escamboapp/app/views/site/ad_detail/shared/_comment_modal.html.haml
= form_tag site_comments_path do
	.modal.fade#commentModal{"tabindex" => "-1", "role" => "dialog", 
	"arial-labelledby" => "commentLabelModal"}
		.modal-dialog{"role"=> "document"}
			.modal-content
				.modal-header
					%button.close{"data-dismiss" => "modal", "aria-label" => "Close"}
						%span{'aria-hidden'=>"true"} &times;
					%h4.modal-title#commentLabelModal Deixe seu comentário
				.modal-body
					.form-group
						%label Comentário
						= text_area :comment, :body, class: "form-control", rows: 5
						= hidden_field :comment, :ad_id, value: @ad.id
				.modal-footer
					%button.btn.btn-default{'data-dismiss' => "modal"} Fechar
					= submit_tag "Enviar", class: "btn btn-primary"

escamboapp/app/views/site/ad_detail/shared/_comments.html.haml
- @ad.comments.each do |comment|
	.row
		.col-xs-12.col-sm-12.col-md-12.col-lg-12
			%span.glyphicon.glyphicon-star
			%span.glyphicon.glyphicon-star
			%span.glyphicon.glyphicon-star
			%span.glyphicon.glyphicon-star
			%span.glyphicon.glyphicon-star-empty
			= comment.member.email
			%span.pull-rigth
				= time_ago_in_words(comment.created_at)
			%p= comment.body
			-if current_member && current_member.id == comment.member.id
				=rating_for_user @ad, current_member, 'quality'
	%hr/

escamboapp/app/views/site/ad_detail/shared/_show.html.haml
.card.mt-4
	= image_tag @ad.picture.url(:large)
	.card-body
		%h3.card-title
			= @ad.title
		%h4
			= humanized_money_with_symbol @ad.price
		%p.card-text
			= @ad.description.html_safe

.well.well-sm
	.ratings
		%p.pull-right 
			= @ad.comments.count	
			comentários 
		= rating_for @ad, 'quality', disable_after_rate: true

.well
	-if member_signed_in?
		.text-right
			%button.btn.btn-success{:type => 'button', "data-toggle" =>"modal", "data-target" => "#commentModal"}
				Deixe um comentário
	-else
		.text-right
			=link_to "Efetue o login para fazer comentário", new_member_session_path, class: "btn btn-success"
	%h1= @ad.id
	= render partial: 'site/ad_detail/shared/comments' 
	= render partial: 'site/ad_detail/shared/comment_modal'